[build]
  publish = "."
  functions = "netlify/functions"

# --- ส่ง /api ไป Function ก่อน (ต้องมาก่อน fallback เสมอ) ---
[[redirects]]
  from = "/api"
  to = "/.netlify/functions/gs-proxy"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gs-proxy"
  status = 200
  force = true

# --- SPA fallback กัน 404 เส้นทางอื่น ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
